name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main  # runs when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Push to Hugging Face Space
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          # clone with authentication
          git clone https://katie2023may:$HF_TOKEN@huggingface.co/spaces/katie2023may/chessboard-recognizer hf_space
          rsync -av --delete ./ hf_space/ --exclude '.git' --exclude '.github'
          cd hf_space
          git add .
          git commit -m "Update from GitHub Actions" || echo "No changes to commit"
          git push https://katie2023may:$HF_TOKEN@huggingface.co/spaces/katie2023may/chessboard-recognizer main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}